AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'aboap'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demoabou-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://dev.azure.com/abouraiss06400'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
